name: ui_kit
description: Design kit
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  data:
    path: ../data
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0
